For #9 - Depends on needs to be an array or an object (apparently) fix.
Running on Ubuntu 20.04 I had the error:
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.drupal.depends_on contains an invalid type, it should be an array, or an object
services.phpmyadmin.depends_on contains an invalid type, it should be an array, or an object